### ISSUE TITLE
Inconveniente al ejecutar el create_workspace

### ISSUE THREAD

**Issue by JSEB99** [OscarSantosMu/azure-ml-workspace-creation#2]
Buen día,

Estuve intentando ejecutar el create_workspace, me tocó instalar azure cli, iniciar sesión y desde ahi ejecutar el workspace. Ahi todo bien, se ejecuto y creo recursos pero al momento de crear los recursos de Machine Learning, me sale el siguiente error ya visualizando el link que me retorna al momento de ejecución por consola.

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "Invalid",
      "message": "Missing dependent resources in workspace json"
    }
  ]
}

Quisiera saber si existe alguna solución a este problema.

**Comment by Underdoge** [comment]
Hi,

I just confirmed this issue arises when using the latest version of the azure-ai-ml python package 1.16.0. A similar issue was reported [here](https://github.com/Azure/azure-cli/issues/28980) with the Azure CLI. 

The workaround for now is installing azure-ai-ml version 1.15.0 instead. To do that, you can edit the 'requirements.txt' file and append '==1.15.0' to the first line to specify that version for the azure-ai-ml package, so in the end your 'requirements.txt' file will look like the following:

```
azure-ai-ml==1.15.0
python-dotenv
```

After that, run 'pip install -r requirements.txt' again, and it should uninstall azure-ai-ml version 1.16.0 and install 1.15.0. Then you should be able to run 'create_workspace.py' without issues.

**Comment by achauhan-scc** [comment]
azure-ai-ml==1.16.1 is released with the fix.
